Portafolio/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Portafolio.Models;

namespace Portafolio.Controllers
{
    public class CoursesController : Controller
    {
        private Cem db = new Cem();

        // GET: Courses
        public async Task<ActionResult> Index()
        {
            var course = db.Course.Include(c => c.Program);
            return View(await course.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Course.FindAsync(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.ProgramId = new SelectList(db.Program, "ProgramId", "Name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CourseId,Name,ProgramId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Course.Add(course);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ProgramId = new SelectList(db.Program, "ProgramId", "Name", course.ProgramId);
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Course.FindAsync(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProgramId = new SelectList(db.Program, "ProgramId", "Name", course.ProgramId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CourseId,Name,ProgramId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProgramId = new SelectList(db.Program, "ProgramId", "Name", course.ProgramId);
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Course.FindAsync(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Course course = await db.Course.FindAsync(id);
            db.Course.Remove(course);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Portafolio/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Portafolio.Models;

namespace Portafolio.Controllers
{
    public class NotesController : Controller
    {
        private Cem db = new Cem();

        // GET: Notes
        public async Task<ActionResult> Index()
        {
            var note = db.Note.Include(n => n.Course);
            return View(await note.ToListAsync());
        }

        // GET: Notes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = await db.Note.FindAsync(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // GET: Notes/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "Name");
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "NoteId,CourseId,Score")] Note note)
        {
            if (ModelState.IsValid)
            {
                db.Note.Add(note);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "Name", note.CourseId);
            return View(note);
        }

        // GET: Notes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = await db.Note.FindAsync(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "Name", note.CourseId);
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "NoteId,CourseId,Score")] Note note)
        {
            if (ModelState.IsValid)
            {
                db.Entry(note).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "Name", note.CourseId);
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = await db.Note.FindAsync(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Note note = await db.Note.FindAsync(id);
            db.Note.Remove(note);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Portafolio/Controllers/PeriodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Portafolio.Models;

namespace Portafolio.Controllers
{
    public class PeriodsController : Controller
    {
        private Cem db = new Cem();

        // GET: Periods
        public async Task<ActionResult> Index()
        {
            return View(await db.Period.ToListAsync());
        }

        // GET: Periods/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Period period = await db.Period.FindAsync(id);
            if (period == null)
            {
                return HttpNotFound();
            }
            return View(period);
        }

        // GET: Periods/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Periods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PeriodId,Name")] Period period)
        {
            if (ModelState.IsValid)
            {
                db.Period.Add(period);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(period);
        }

        // GET: Periods/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Period period = await db.Period.FindAsync(id);
            if (period == null)
            {
                return HttpNotFound();
            }
            return View(period);
        }

        // POST: Periods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PeriodId,Name")] Period period)
        {
            if (ModelState.IsValid)
            {
                db.Entry(period).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(period);
        }

        // GET: Periods/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Period period = await db.Period.FindAsync(id);
            if (period == null)
            {
                return HttpNotFound();
            }
            return View(period);
        }

        // POST: Periods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Period period = await db.Period.FindAsync(id);
            db.Period.Remove(period);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Portafolio/Controllers/RoleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Portafolio.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portafolio.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Roles
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
    }
}

Portafolio/Views/Users/Experiences.cshtml
@{
    ViewBag.Title = "Experiences";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>¡Experiencias!</h2>

<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <h2 class="section-heading">BigData en Granada</h2>

                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis id molestie ligula. Suspendisse potenti. 
                    Curabitur lorem tellus, rhoncus non elit nec, aliquet commodo metus. Vivamus a augue nec lacus bibendum aliquam
                     eu non eros. Proin congue nibh at felis blandit hendrerit. Orci varius natoque penatibus et magnis dis parturient 
                    montes, nascetur ridiculus mus. Proin egestas vitae felis mattis iaculis. Integer sit amet auctor mauris, 
                    et consequat elit. Sed lobortis tellus urna. Aenean in maximus urna. Vivamus lectus arcu, ultricies in dui ut,
                     bibendum venenatis tortor. Phasellus tempus urna vitae lorem venenatis mollis. Nullam tempor id nunc sit amet
                     tristique. Mauris a neque accumsan, suscipit nisl id, fringilla tellus. 
                </p>
                <span class="caption text-muted">
                    "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
                </span>

                <p>
                    Publicado por
                    <a href="#">Cindy Contador</a>
                </p>
            </div>

            <div class="col-lg-8 col-md-10 mx-auto">
                <h2 class="section-heading">Gestión de proyectos en México</h2>

                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis id molestie ligula. Suspendisse potenti.
                    Curabitur lorem tellus, rhoncus non elit nec, aliquet commodo metus. Vivamus a augue nec lacus bibendum aliquam
                    eu non eros. Proin congue nibh at felis blandit hendrerit. Orci varius natoque penatibus et magnis dis parturient
                    montes, nascetur ridiculus mus. Proin egestas vitae felis mattis iaculis. Integer sit amet auctor mauris,
                    et consequat elit. Sed lobortis tellus urna. Aenean in maximus urna. Vivamus lectus arcu, ultricies in dui ut,
                    bibendum venenatis tortor. Phasellus tempus urna vitae lorem venenatis mollis. Nullam tempor id nunc sit amet
                    tristique. Mauris a neque accumsan, suscipit nisl id, fringilla tellus.
                </p>
                <span class="caption text-muted">
                    "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
                </span>

                <p>
                    Publicado por
                    <a href="#">Patricio Soto</a>
                </p>
            </div>
        </div>
    </div>
</article>

Portafolio/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card text-center">
    <div class="card-header">
        Mis acciones
    </div>
    <div class="card-body">
        <h5 class="card-title">Bienvenido @ViewBag.Name</h5>
        <p class="card-text"></p>
@if (ViewBag.displayMenu == "Yes")
{
        @Html.ActionLink("Administrar Roles", "Index", "Role", null ,new { @class = "btn btn-sm btn-secondary" }) 
        @Html.ActionLink("Administrar Países", "Index", "Countries", null ,new { @class = "btn btn-sm btn-secondary ml-5" })<br /><br />
        @Html.ActionLink("Administrar Centros de estudio", "Index", "StudyCenters", null,new { @class = "btn btn-sm btn-secondary" }) 
        @Html.ActionLink("Administrar Programas de intercambio", "Index", "Programs", null, new { @class = "btn btn-sm btn-secondary ml-5" })<br /><br />
        @Html.ActionLink("Administrar Cursos", "Index", "Courses", null ,new { @class = "btn btn-sm btn-secondary" }) 
        @Html.ActionLink("Administrar Notas", "Index", "Notes", null ,new { @class = "btn btn-sm btn-secondary ml-5" })<br /><br />
        @Html.ActionLink("Administrar Periodos de programas", "Index", "Periods", null ,new { @class = "btn btn-sm btn-secondary" }) 
        @Html.ActionLink("Administrar Estados de programas", "Index", "ProgramStatus", null ,new { @class = "btn btn-sm btn-secondary ml-5" })<br /><br />
        @Html.ActionLink("Ver información de familias", "Index", "FamilyInfoes", null ,new { @class = "btn btn-sm btn-secondary" })
        @Html.ActionLink("Administrar estados de postulaciones", "Index", "ApplicationStatus", null, new { @class = "btn btn-sm btn-secondary ml-5" })<br /><br />
        @Html.ActionLink("Administrar Postulaciones", "Index", "StudentApplications", null, new { @class = "btn btn-sm btn-secondary" })
        @Html.ActionLink("Cambiar contraseña", "ChangePassword", "Manage", null, new { @class = "btn btn-sm btn-info ml-5" })<br /><br />
}
@if (ViewBag.displayStudentMenu == "Yes")
{
    @Html.ActionLink("Postular a programa de intercambios", "PublicatedPrograms", "Programs", null, new { @class = "btn btn-sm btn-secondary ml-5" })
    @Html.ActionLink("Ver mis postulaciones", "Index", "StudentApplications", null, new { @class = "btn btn-sm btn-secondary ml-5" })<br /><br />
    @Html.ActionLink("Cambiar contraseña", "ChangePassword", "Manage", null, new { @class = "btn btn-sm btn-info ml-5" })<br /><br />
}
@if (ViewBag.displayCelAdminMenu == "Yes")
{
    <h3>
        <li>@Html.ActionLink("Registrar un centro de estudio", "Create", "StudyCenters")</li>
    </h3>
}
@if (ViewBag.displayFamilyMenu == "Yes")
{
    @Html.ActionLink("Subir certificados", "Index", "Role", null, new { @class = "btn btn-sm btn-secondary" })<br /><br />
    @Html.ActionLink("Ver postulaciones de alumnos", "Index", "Role", null, new { @class = "btn btn-sm btn-secondary" })<br /><br />
    @Html.ActionLink("Cambiar contraseña", "ChangePassword", "Manage", null, new { @class = "btn btn-sm btn-info ml-5" })<br /><br />
}
@if (ViewBag.displayInternationalRelationsMenu == "Yes")
{
    <h3>
        <li>@Html.ActionLink("Administrar Programas de intercambio", "Index", "Programs")</li>
    </h3>
}
    </div>
    <div class="card-footer text-muted">
        @DateTime.Now
    </div>
</div>